name: 'AWS SAM Deploy Enhancement'
description: 'Deploys AWS SAM Stack without split big file'
author: 'Neo Xie <xieliangchang@gmail.com>'
branding:
  icon: 'upload-cloud'
  color: 'orange'
runs:
  using: 'docker'
  image: 'Dockerfile'
